### ISSUE TITLE
Pands error on init

### ISSUE THREAD

**Issue by Schneider1** [qkitgroup/qkit#38]
When I init qkit, I get the following error in a subthread:

```
Exception in thread Thread-6:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda2\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\qkit\qkit\core\s_init\S80_load_file_service.py", line 16, in _load_file_service
    qkit.dbv = DatabaseViewer()
  File "C:\qkit\qkit\core\lib\file_service\database_viewer.py", line 59, in __init__
    self._initiate_basic_df()
  File "C:\qkit\qkit\core\lib\file_service\database_viewer.py", line 79, in _initiate_basic_df
    self.df = self.df[['datetime', 'name', 'run', 'user']]
  File "C:\ProgramData\Anaconda2\lib\site-packages\pandas\core\frame.py", line 1958, in __getitem__
    return self._getitem_array(key)
  File "C:\ProgramData\Anaconda2\lib\site-packages\pandas\core\frame.py", line 2002, in _getitem_array
    indexer = self.loc._convert_to_indexer(key, axis=1)
  File "C:\ProgramData\Anaconda2\lib\site-packages\pandas\core\indexing.py", line 1231, in _convert_to_indexer
    raise KeyError('%s not in index' % objarr[mask])
KeyError: "['datetime' 'name' 'run' 'user'] not in index"
```

**Comment by TimWolz** [comment]
fixed: an empty data frame is generated if there are no h5 files in the data directory
